### PR TITLE
707 log slow checkpoints

### PR DESCRIPTION
**Pull request by mitesh-gosavi**
**Description of changes**

The —checkpoint flag has been added to the argument parser for the mplotqueries. The parser, on receiving the —checkpoint flag, searches for loglines containing the “Checkpoint took” token (for reference, see mongodb/mongo@f3eb442). On encountering the token, the parser parses the token after “took” and typecast it to an integer to get the duration followed by mapping the details on to the graph.

**Testing**

The following testing tools have been used to test the newly added code:

Tox
Flake8
iSort
Doc8

The test result of a code coverage can be seen in table below:

> **Name Stmts Miss Cover**

---------------------------------------------------------------------

> mtools/mplotqueries/mplotqueries.py 400 93 77%
> mtools/util/logevent.py 510 2 99%

**Version Information**

| macOS | 10.14.5	|
| mongod	| v4.0.10	|
| MongoDB shell	| v4.0.10	|
| Python	| 2.7.10	|

### CODE REVIEW

**Comment by stennie** [comment]
@mitesh-gosavi Thanks for the round of PRs!

It would be easier to review & merge these if you could:
 - Keep the commits distinct (this PR includes the same commits as #704, #705, ...). Ideally each PR should only have commits related to a single feature/change to avoid conflicts.
 - Rebase on current `develop` branch (NB: since you last updated your fork we have dropped support for Python 2.7 and added Python 3.7).

Also, please  advise if there is a specific order the PRs should be applied in due to dependences.

Regards,
Stennie

**Comment by stennie** [comment]
@mitesh-gosavi One more request: can you rename `mtools/test/logfiles/mongod.log` to something more descriptive?

If this is used for a single feature test you could name it after the feature with some suggestion of the server version used, for example: `mongod_4.0.10_slowcheckpoints.log`.  If the log is used for multiple tests it would be great to extract the minimum log lines required for each test, in order to potentially speed up test runs and make it easier to update tests in future.

Thanks,
Stennie

**Comment by stennie** [comment]
@mitesh-gosavi Missed one more todo: any new flags or behaviour also needs to be documented. See `doc/*.rst`.

Thanks,
Stennie

**Comment by mitesh-gosavi** [comment]
> @mitesh-gosavi Thanks for the round of PRs!
> 
> It would be easier to review & merge these if you could:
> 
> * Keep the commits distinct (this PR includes the same commits as #704, #705, ...). Ideally each PR should only have commits related to a single feature/change to avoid conflicts.
> * Rebase on current `develop` branch (NB: since you last updated your fork we have dropped support for Python 2.7 and added Python 3.7).
> 
> Also, please advise if there is a specific order the PRs should be applied in due to dependences.
> 
> Regards,
> Stennie

@stennie Yes, I noticed the recent changes in PRs and branches. I am going to close these PRs(from #704 to #709) and create new ones without any code conflict from new branches. I will make sure to add documentation in the new PRs. Also, I will rename the mtools/test/logfiles/mongod.log as suggested. Thanks! :)

**Pull request closed without merging**
