### PR TITLE
Adjust plot colors.

### LINKED ISSUE #453: mplotqueries default colors could be better
The current order is:
- #000000 black
- #00FF00 green
- #0000FF blue
- #FF0000 red
- #01FFFE cyan
- #FFA6FE light magenta
- #FFDB66 yellowish
- #006401 dark green
- #010067 dark blue
- #95003A dark red
- #007DB5 pastel blue
- #FF00F6 magenta
- #FFEEE8 light beige
- #774D00 brown

Since black is used for the edges of the circles in scatterplots, it should never be used for the interior of the circles, because the result is often an indistinguishable black blob.

The first few colours should not be green or red, since these have good/bad connotations, and will always appear "the most" on plots.  So it'd be best to start with some "neutral" colours, like blue, magenta, cyan, before resorting to red and green.

White can't be used since it's the background color.  However it would be possible to have 1 or 2 shades of grey (eg. #808080, or #555555 and #AAAAAA, or #3f3f3f and #bdbdbd).

After this can come the rest of the existing colors.

So the suggestion is to have:
- #0000FF blue
- #FF00F6 magenta
- #01FFFE cyan
- #bdbdbd light gray
- #3f3f3f dark gray
- #FF0000 red
- #00FF00 green
- #FFA6FE light magenta
- #FFDB66 yellowish
- #006401 dark green
- #010067 dark blue
- #95003A dark red
- #007DB5 pastel blue
- #FFEEE8 light beige
- #774D00 brown

### PR DESCRIPTION
**Pull request by devkev**
Specifically: avoid black, move colors with connotations (red, green) to be
used less often, and add two greys.

Fixes #453.

### CODE REVIEW

**Comment by braz** [comment]
I'd be very conscious of colour blindness when suggesting red. Blue -> Green spectrum is much more friendly in these cases.
http://www.cs.ubc.ca/~tmm/courses/547-15/#chap10 particularly http://www.personal.psu.edu/faculty/c/a/cab38/ColorSch/ASApaper.html

Checkout these simulators:
http://rehue.net/
http://www.color-blindness.com/
http://www.etre.com/tools/colourblindsimulator/

**Comment by devkev** [comment]
Can you please move this to the issue, #453?  I don't want to have dual conversations.  :)

**Comment by braz** [comment]
Sorry Kev, I missed out on that Issue. I'll move it there instead ! :-)

**Comment by stennie** [comment]
Merged via PR#503

**Pull request closed without merging**
