### PR TITLE
Fix/bugre #764 json serialize crash w bytes instead of str in pattern.py

### LINKED ISSUE #764: mloginfo --queries crash "TypeError: Object of type bytes is not JSON serializable"
### Actual/current behavior
Crash when running.
```
mloginfo --queries ./mongod.log  

# or (with no differente output)
mloginfo --verbose --queries ./mongod.log
```

Crashes when running with `--queries`. 
But, does NOT crash running with `--connections` for example. So i think it's related to some specific query parameter or values.

I can confirm that the problem reported at #684 still exist with the latest version of mtools (tested with latest mtools 1.6.0 release, also with develop branch)  and python 3.7.6  (before was using 3.6 with same results, upgraded as a trial to fix the issue :), but no.

```
✔ ~/dsv/mtools/mtools/util [develop|✚ 1…1]
11:05 $ mlogfilter --version
mtools version 1.6.1-dev || Python 3.7.6 (default, Dec 30 2019, 19:38:28)
[Clang 11.0.0 (clang-1100.0.33.16)]
```

### Steps to reproduce the actual/current behavior
Simply run: `mloginfo --verbose --queries ./mongod.log` generates the crash with this traceback.

```
Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 11, in <module>
    load_entry_point('mtools', 'console_scripts', 'mloginfo')()
  File "$HOME/dsv/mtools/mtools/mloginfo/mloginfo.py", line 100, in main
    tool.run()
  File "$HOME/dsv/mtools/mtools/mloginfo/mloginfo.py", line 95, in run
    section.run()
  File "$HOME/dsv/mtools/mtools/mloginfo/sections/query_section.py", line 81, in run
    pattern=le.pattern, duration=le.duration,
  File "$HOME/dsv/mtools/mtools/util/logevent.py", line 474, in pattern
    self._pattern = self._find_pattern('filter: ')
  File "$HOME/dsv/mtools/mtools/util/logevent.py", line 989, in _find_pattern
    return json2pattern(search_str)
  File "$HOME/dsv/mtools/mtools/util/pattern.py", line 96, in json2pattern
    return json.dumps(doc, sort_keys=True, separators=(', ', ': '))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | tested with 1.6.0 release and with 'develop' branch 
| MongoDB server   | logs are from MongoDB Atlas 4.0.13 primary server
| Operating system | running mtools locally on my mac OS X 10.14.6

### Others..

I'll try to reduce the log to reasonable size and sanitise it while still getting it to generate the error (now it's around 4GB and has a lot of private data). And if i get the time, try to troubleshoot it a little and report back or suggest a possible fix if i'm able to do it.

### PR DESCRIPTION
**Pull request by bugre**
## Description of changes
in `mtools/utils/pattern.py` a behavior change from py2 to py3 (string.encode('utf-u')) generates a byte string output and not a standart unicode string. And thus, JSON can't serialize this output later.

As mtools 1.6.0 no longer is Python 2.7 compatible, and in Python3 all strings are unicode the part that generates the problem isn't needed anymore. Also used the opportunity to remove 'six' package (introduced on Python 2 to Python3 transition).

Also added `ensure_ascii=False` to json.dumps call so that unicode chars are printed as 'chars' and not as octa or hex char codes.

```       
 return json.dumps(doc, sort_keys=True, separators=(', ', ': '), ensure_ascii=False)
```

## Testing
i've added an additional test case in `mtools/utils/pattern.py`  for this situation

```

    ##
    ## 20191231 - bugre - issue#764 - adding some more test cases.. based on our mongodb logs (mongod 4.0.3)
    ##
    s = (r'{_id: ObjectId(\'528556616dde23324f233168\'), curList: [ "€", "XYZ", "Krown"], allowedSnacks: 1000 }')
    print(json2pattern(s))

```

Fixes #764

### CODE REVIEW

**Comment by stennie** [comment]
@bugre Thanks for investigating and following through with a PR! :)

**Comment by bugre** [comment]
Hi @stennie , 
I've made a couple of changes on the last commit
- improve (i hope) the __main()__ test pattern/verification process, adding the pattern and the expected 'result' to a dict to easier spot code changes that change/break the expected result.  (*1)
- add a regex that simplifies "{... "attrib" : ["val1", "val2", "3"],...}" to "{..."atrib" : [1],... }". 
  I've tested this change as far i could and know the code (that is not much) so, if you could double check it would be best. Maybe add a note about it on next release , asking for extra care.
  This change, instead of doing it with a regex, it could probably also be made inside the 'def _decode_pattern_list(...)' code, but i wasn't sure the side effects of it.
--
(*1) This is a sample output, if you run only the "util/pattern.py" with the new pattern/result dict. Let me know if you would like that i revert it to the original code.
```
✔ ~/dsv/mtools [fix/bugre-#764_JSONSerialize_crash_w_bytes|✚ 1⚑ 3] 
07:20 $ /usr/local/bin/python3 /Users/werner.michels/dsv/mtools/mtools/util/pattern.py
OK:
  Input : {d: {$gt: 2, $lt: 4}, b: {$gte: 3}, c: {$nin: [1, "foo", "bar"]}, "$or": [{a:1}, {b:1}] }
  Expect: {"$or": [{"a": 1}, {"b": 1}], "b": 1, "c": {"$nin": 1}, "d": 1}
  Output: {"$or": [{"a": 1}, {"b": 1}], "b": 1, "c": {"$nin": 1}, "d": 1}
ERROR ******* :
  Input : {aa: {$gt: 22, $lt: 4}, "b": {$nin: [1, 2, 3]}, "$or": [{a:1}, {b:1}] }
  Expect: {"$or": [{"a": 1}, {"b": 1}], "a": 1, "b": {"$nin": 1}}
  Output: {"$or": [{"a": 1}, {"b": 1}], "aa": 1, "b": {"$nin": 1}}

```

Let me know what you think.

**Comment by bugre** [comment]
After running the 'fixed' code over a few days of logs, found two situations that got me the wrong results, because i wasn't correctly protecting the starting of the list with regex. So i've added a positive lookahead to asure that after the '[' i only get space and than MUST a " (quote) exist.

Have also added a new test case.

Hope that this does generate a better and more precise result.

Fix #768

**Comment by stennie** [comment]
@bugre I think there is still some work to do on test cases for patterns (regex with escaped `[`s, for example). However, `mloginfo` previously silently skipped these so that isn't new behaviour.

I added your debug output to `mloginfo --debug` via 200b0a1. The output is rather verbose but could be useful for debugging log patterns.

Regards,
Stennie

**Comment by bugre** [comment]
Thanks @stennie. Nice solution with '--debug'.

I've a few really busy weeks ahead, so it probably will take some time until i can get back to this code. But i'll have a look as soon i can.

**Pull request merged**
